# Generated by Django 5.2.6 on 2025-09-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("capacity", models.IntegerField(help_text="Maximum capacity")),
                (
                    "facilities",
                    models.TextField(
                        blank=True,
                        help_text="Available facilities (projector, sound system, etc.)",
                    ),
                ),
                (
                    "available_for_carnival",
                    models.BooleanField(
                        default=True, help_text="Available for Thursday Carnival"
                    ),
                ),
                (
                    "available_for_creativa",
                    models.BooleanField(
                        default=True, help_text="Available for Creativa events"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReservationConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Resolution"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated to Super Admin"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Activity"),
                            ("carnival", "Thursday Carnival"),
                            ("creativa", "Creativa Event"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "expected_attendees",
                    models.IntegerField(help_text="Expected number of attendees"),
                ),
                ("purpose", models.TextField(help_text="Purpose of the reservation")),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Special equipment or setup requirements"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the reservation"
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(
                        default=0, help_text="Priority score for conflict resolution"
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="activities.activity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
    ]
