# Generated by Django 5.2.6 on 2025-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("team_description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_logos/"
                    ),
                ),
                (
                    "previous_contributions",
                    models.TextField(help_text="Previous contributions to the faculty"),
                ),
                (
                    "expected_contribution",
                    models.TextField(help_text="Expected contribution to the faculty"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "rejected"),
                            ("meeting_requested", "Meeting Requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the activity"
                    ),
                ),
                ("timeline_published", models.BooleanField(default=False)),
                ("timeline_publish_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "announcement_text",
                    models.TextField(
                        blank=True, help_text="Custom announcement text for timeline"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured activities appear first"
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "-published_date"],
            },
        ),
    ]
