# Generated by Django 5.2.6 on 2025-09-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_datetime", models.DateTimeField()),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["proposed_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Meeting Requested"),
                            ("scheduled", "Meeting Scheduled"),
                            ("completed", "Meeting Completed"),
                            ("cancelled", "Meeting Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=30, help_text="Meeting duration in minutes"
                    ),
                ),
                (
                    "meet_link",
                    models.URLField(blank=True, help_text="Google Meet link"),
                ),
                (
                    "meet_id",
                    models.CharField(
                        blank=True, help_text="Google Meet ID", max_length=100
                    ),
                ),
                (
                    "admin_notes_before",
                    models.TextField(
                        blank=True, help_text="Admin notes before meeting"
                    ),
                ),
                (
                    "admin_notes_after",
                    models.TextField(blank=True, help_text="Admin notes after meeting"),
                ),
                (
                    "student_notes",
                    models.TextField(blank=True, help_text="Student notes/questions"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Decision"),
                            ("approved", "Activity Approved"),
                            ("rejected", "Activity Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="activities.activity",
                    ),
                ),
            ],
        ),
    ]
